---
title: "Assignment_3"
author: "Yeswanth Siripurapu"
date: "2023-10-15"
output:
  pdf_document: default
  html_document: default
---

```{r setup}

UniversalBank <- read.csv("D:/UniversalBank (1).csv")
summary(UniversalBank)
library(caret)
library(ISLR)
library(e1071)
library(dplyr)
library(class)
library(reshape2)
library(ggplot2)
library(gmodels)
library(lattice)
```

```{r}
#converting variables
UniversalBank$Personal.Loan <- factor(UniversalBank$Personal.Loan)
UniversalBank$Online <- factor(UniversalBank$Online)
UniversalBank$CreditCard <- factor(UniversalBank$CreditCard)
df= UniversalBank
```

```{r}
#Question 1

#Create a pivot table for the training data with Online as a column variable, 
#CC as a row variable, and Loan as a secondary row variable.

set.seed(64060)
Train_index <- createDataPartition(df$Personal.Loan, p = 0.6, list = FALSE)
train.df = df[Train_index,]
validation.df = df[-Train_index,]

mytable <- xtabs(~ CreditCard + Online + Personal.Loan , data = train.df)
ftable(mytable)

```
```{r}
#Question 2

#Consider the task of classifying a customer who owns a bank credit card and is 
#actively using online banking services. Looking at the pivot table, what is the
#probability that this customer will accept the loan offer? [This is the
#probability of loan acceptance (Loan = 1) conditional on having a bank credit 
#card (CC = 1) and being an active user of online banking services(Online = 1)].


probability = 59/(59+479)
probability

```
```{r}
#Question 3

#Create two separate pivot tables for the training data. One will have Loan 
#(rows) as a function of Online (columns) and the other will have Loan (rows) as
#a function of CC.

table(Personal.Loan = train.df$Personal.Loan, Online = train.df$Online)

table(Personal.Loan = train.df$Personal.Loan, CreditCard = train.df$CreditCard)
table(Personal.Loan = train.df$Personal.Loan)
```

```{r}
#Question 4

#Compute the following quantities [P(A | B) means
#“the probability of A given B”]: 

#i. P(CC = 1 | Loan = 1) (the proportion of credit card holders among the loan 
#acceptors) 
Probablity1 <- 93/(93+195)
Probablity1

#ii. P(Online = 1 | Loan = 1)  
Probablity2 <- 179/(179+109)
Probablity2

#iii. P(Loan = 1) (the proportion of loan acceptors)  
Probablity3 <- 288/(288+2712)
Probablity3
#iv. P(CC = 1 | Loan = 0)  
Probablity4 <- 788/(788+1924)
Probablity4

#v. P(Online = 1 | Loan = 0) 
Probablity5 <- 1631/(1631+1081)
Probablity5

#vi. P(Loan = 0) 
Probablity6 <- 2712/(2712+288)
Probablity6
```

```{r}
#Question 5

#Use the quantities computed above to compute the naive Bayes probability 
#P(Loan = 1 | CC= 1, Online = 1).


Task5Probablity <- (Probablity1*Probablity2*Probablity3)/
  ((Probablity1*Probablity2*Probablity3) +(Probablity4*Probablity5*Probablity6))

Task5Probablity 
```

```{r}
#Question 6

#Compare this value with the one obtained from the pivot table in (B). Which is 
#a more
#accurate estimate?

#Answer:
  
# Value we got from question 2 was 0.1096654 and in the question 5  is 0.1087106
#are almost same.The only differencebetween by the exact method and naive bayes
#method is the exact method would need the exact same independent variable 
#classification to predict, whereas the naive bayes method does not. We can 
#confirm that the value get from the question 2 is more accurate since we have 
#taken the exact values from the pivot table.

#Question 7

#Which of the entries in this table are needed for computing P(Loan = 1 | CC = 1, Online = 1)? Run naive Bayes on the data. Examine the model output on training data, and find the entry that corresponds to P(Loan = 1 | CC = 1, Online = 1). Compare this to the number you obtained in (E).

nb.model <- naiveBayes(Personal.Loan~ Online + CreditCard, data = train.df)
To_Predict=data.frame(Online=1, CreditCard= 1)
predict(nb.model, To_Predict,type = 'raw')

# The value we got from question 7  is 0.08463445 and value derived from the task 5 is 0.1087106.
# The result is almost same that we got from Task5.
# There is only a minute difference because of the rounding.
# The difference will not effect the rank order of the output.

```